version: '3'

services:
  mongo:
    image: mongo:4.0.9-xenial
    restart: always
    volumes:
      - ./data/db:/data/db
    # Uncomment the lines below to enable introspection into the mongodb
    # with external tools.
    # ports: 
    #   - "27017:27017"
    networks:
      - djanenetwork

  djaneio: 
    build: .
    depends_on: 
      - mongo
    environment:
      DB_HOST: mongo
    ports: 
      - "3000:3000"
    command: bash -c "./wait-for-it.sh mongo:27017 -t 30 -- npm run migrate && npm start"
    networks: 
      - djanenetwork

networks:
  djanenetwork: 
